#pragma once
#define EXPANSION_RATIO 1.05
#define MAX_BUFFER_SIZE 256
#define MAX_NO_SHIFT MAX_BUFFER_SIZE
#define MIN_OCCUPANCY 0.5
#define MAX_OCCUPANCY 0.8
#define GLOBAL_ERROR 256
#define NO_SEGMENT 128
#define SEARCH_BOUND_RATIO 0.6
#define FANOUT_BP 256
#define AUTO_TUNE_RATE 0.1
#define AUTO_TUNE_SIZE AUTO_TUNE_RATE * TIME_WINDOW
#define MIN_BOUND
#define TUNE
